### ISSUE TITLE
django-smart-selects doesn't work in templates

### ISSUE THREAD

**Issue by dezinfo** [digi604/django-smart-selects#116]
I have a problem with django-smart-selects usage. In the admin panel, django-smart-selects works correctly but in templates there is an error.

Uncaught ReferenceError: chainedfk is not defined

It looks like django can't find chainedfk

**Comment by vahgar** [comment]
I do have same problem :(

**Comment by julianx** [comment]
I was able to fix this using `<script src="{% static 'smart-selects/admin/js/chainedfk.js' %}"></script>` in the templates, as suggested by Zee in http://stackoverflow.com/questions/35338665/django-smart-selects-doesnt-work-in-templates/35772760

**Comment by SalahAdDin** [comment]
@digi604 What's about this great package?

**Comment by toweralaka** [comment]
i have a similar problem but without error; selection has no effect on chained field- the field is empty

**Comment by bgarcial** [comment]
I have the same problem of @toweralaka in my frontend form the chained effect is not works, is empty, via admin the chained effect works.

**Comment by SalahAdDin** [comment]
But i have these problem via admin. I didn't test  it in templates.

**Comment by blag** [comment]
Should be fixed with #137.

**Comment by davideghz** [comment]
Hi, I still get this error in the frontend while it's working great in the admin:

> jQuery.Deferred exception: chainedfk is not defined ReferenceError: chainedfk is not defined
>     at HTMLDocument.<anonymous> (http://localhost:8000/orders/3/:53:17)
>     at j (https://code.jquery.com/jquery-3.1.1.min.js:2:29948)
>     at k (https://code.jquery.com/jquery-3.1.1.min.js:2:30262) undefined


> Uncaught ReferenceError: chainedfk is not defined
>     at HTMLDocument.<anonymous> ((index):53)
>     at j (jquery-3.1.1.min.js:2)
>     at k (jquery-3.1.1.min.js:2)

**Comment by vahgar** [comment]
Just try including chainedfk.js and chainedm2m.js file in your template HTML separately.

**Comment by blag** [comment]
That workaround would be unnecessary - and the Python code would be **greatly** simplified - if the JS code was moved into a separate file.

PR #96 did that but it was outdated and wouldn't merge cleanly. I don't have the time to fix this myself but I'm happy to look over and merge a new PR that externalizes the javascript code.

If anybody has the time and energy to do that I would be very grateful. :smiley:

**Comment by AmiNadim** [comment]
**Issue Resolved Manually**


just add these three lines to the <head> section of your html template
```
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script type="text/javascript" src="{% static '/smart-selects/admin/js/chainedfk.js' %}"></script>
    <script type="text/javascript" src="{% static '/smart-selects/admin/js/bindfields.js' %}"></script>
```

these are the links used in django admin.

**Comment by SalahAdDin** [comment]
@blag i think you have to re-open this.

**Comment by blag** [comment]
@SalahAdDin This issue was resolved, why do I need to reopen this?

**Comment by Fadykhallaf** [comment]
@AmiNadim thanks a lot it works with me now.

**Comment by alohapinilla** [comment]
@AmiNadimi it works with your solution, thanks!

**Comment by arkadybruk** [comment]
I'm agree with @SalahAdDin. The problem is still reproducable.
bindfields.js:12 Uncaught ReferenceError: chainedfk is not defined
Django 2.0.3

**Comment by awwester** [comment]
I get the Uncaught Reference error as well still, I have the static files loaded in the correct order:

```
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/smart-selects/admin/js/chainedfk.js"></script>
<script type="text/javascript" src="/static/smart-selects/admin/js/chainedm2m.js"></script>
<script type="text/javascript" src="/static/smart-selects/admin/js/bindfields.js"></script>
```

but get the same error listed above:
```
Uncaught ReferenceError: chainedm2m is not defined
    at initItem (bindfields.js:14)
    at HTMLSelectElement.<anonymous> (bindfields.js:25)
    at Function.each (jquery.min.js:2)
    at bindfields.js:24
    at dispatch (jquery.min.js:3)
    at r.handle (jquery.min.js:3)
```
python 2.7.13
django 1.11.0
django-smart-selects 1.5.4
jquery 2.2.3

**Comment by SalahAdDin** [comment]
Open a new Issue.

**Comment by blag** [comment]
@awwester: Maintainer here, please check to see if you have this problem with the branch I mention in [this comment](https://github.com/digi604/django-smart-selects/issues/253#comment-377007803). If that branch fixes you issue, please post back letting me know and I’ll merge it into `master` and cut a new release to PyPI.

On the other hand, if you are reasonably sure you are experiencing *this* issue, I am happy to reopen it - please don’t open a new issue. Just let me know.

@SalahAdDin: please refrain from instructing other users unless you would like to help maintain this project (and I would very much appreciate the help). Thanks! 😁

**Comment by awwester** [comment]
@blag yeah that branch worked, thanks.

**Comment by blag** [comment]
Glad to hear that branch worked for you. I'm waiting for the dust to settle on #56 and #253 before merging to `master` and cutting a new release to PyPI. Sorry for the wait.

**Comment by mightym** [comment]
@blag fixes the issue for me too! thanks for the hint

**Comment by jrthorne** [comment]
Just a note on @AmiNadimi solution. He has but a leading slash in his loading of static files. This will cause a "Suspicious Operation" Error on the live server. Make sure you have 
<script type="text/javascript" src="{% static 'smart-selects/admin/js/chainedfk.js' %}"></script>
<script type="text/javascript" src="{% static 'smart-selects/admin/js/bindfields.js' %}"></script>
and *not* with a slash before smart-selets!

**Comment by nameisnot** [comment]
@AmiNadim Thanks to your suggestions it's now working in **templates too**. But facing one problem. The **Admin** pages behave correctly even when "**off-line**" (i.e. the dependent field values correctly appear on drop down). But with templates, (in off-line mode) there are no values on drop down, even as the **parent field values are appearing and are selected**.

What am I missing?

**A thought**: Can the "scripts" be made part of the larger game (like, as has been done with **js-unlinting-fixes**?

I am using **Django 2.0.6 and smart-selects 1.5.4 (Python 3.6)**. **js-unlinting-fixes** are installed.
